language: node_js

node_js:
  - "10.15.3"

script:
  - node --version
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $VIRTUALIZATION
  local_dir: build
  keep_history: true
  on:
    branch: master

git:
  depth: 10
